### ISSUE TITLE
Governor issues + Smartass Support?

### ISSUE THREAD

**Issue by benbristow** [Quarx2k/android_kernel_asus_padfone_s#1]
Hey there,

I've noticed some weird performance issues when the interactive governor is enabled with
the Padfone S PF500KL.

Game performance is poor compared to say, the conservative governor.
Also randomly when unlocking the device I notice the device becomes really slow and can either be fixed by somehow managing to reach the governor options or rebooting the device.

Would it be possible to patch in the Smartass/Smartassv2 governors or some others?
I might see if I can do it myself, but it seems like something useful to add to the kernel.
- Ben.

**Comment by Quarx2k** [comment]
Hello. Do you use latest builds? Because bug after unlock should be fixed already.

**Comment by benbristow** [comment]
Hey Quarx,

Would it be safe to just download the latest ZIP and install it without
a fresh install?

**Comment by Quarx2k** [comment]
Yes, but anyway please make backup.  You can also install update from CMUpdater.

**Comment by benbristow** [comment]
Awesome.

By the way this is giving a 404 error. Just a heads-up. Thanks again.
http://download.quarx.cm-for.us/roms/t00n-cm12.1/cm-12.1-20150620-NIGHTLY-t00n.zip

**Comment by Quarx2k** [comment]
Strange, i just clicked on link and it works.
You can download also directly from
http://quarx2k.ru/buildbot/roms/t00n-cm12.1/

On Sun, Jun 21, 2015 at 4:02 PM, Ben Bristow notifications@github.com
wrote:

> Awesome.
> 
> By the way this is giving a 404 error. Just a heads-up. Thanks again.
> 
> http://download.quarx.cm-for.us/roms/t00n-cm12.1/cm-12.1-20150620-NIGHTLY-t00n.zip
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Quarx2k/android_kernel_asus_padfone_s/issues/1#issuecomment-113881356
> .

## 

Sincerely, Nickolay Semendyaev (Quarx2k)

**Comment by benbristow** [comment]
Seems to be working now,

Don't know what happened there.

**Comment by benbristow** [comment]
Update worked fine through CMUpdate.
Fingers cross it fixes the issues I was having.

Other than that your builds are practically flawless.

**Comment by Quarx2k** [comment]
But if you want add Smartass etc, feel free do Pull Request ;)
