### ISSUE TITLE
About the build

### ISSUE THREAD

**Issue by hsucw** [Quarx2k/android_kernel_asus_padfone_s#2]
Hi, I am trying to customized my own kernel for padfone S.
I checkout the newest cm-12.1 and `make pf500kl-perf_defconfig`
Then, flash the `boot.img` into the device.

In general, it is fine and works functionally.
But the _WIFI_ cannot open, I guess something missing.
How do I solve this problem?

The following is the built dtb (14).

---

msm8974pro-ab-pm8941-a90-evb0.dtb 
msm8974pro-ab-pm8941-a91-mp.dtb
msm8974pro-ab-pm8941-a91-sr3.dtb
msm8974pro-ab-pm8941-pf500kl-er1.dtb
msm8974pro-ab-pm8941-a90-evb.dtb
msm8974pro-ab-pm8941-a91-pr.dtb
msm8974pro-ab-pm8941-a91-sr4.dtb
msm8974pro-ab-pm8941-pf500kl-er2_2.dtb
msm8974pro-ab-pm8941-a91-er1.dtb
msm8974pro-ab-pm8941-a91-sr1.dtb
msm8974pro-ab-pm8941-a91-sr5.dtb
msm8974pro-ab-pm8941-pf500kl-pr.dtb

The size of the zImage is 5,475,288 bytes.

Thanks for any suggestion!

**Comment by Quarx2k** [comment]
If you changed wifi driver or configs, you should update them in /system too.

**Comment by hsucw** [comment]
I download the nightly build ROM (20150809) and extract the `boot.img`.
It seems no problem to replace the customized kernel & dt.img. 
Thanks for your information!!
